# Generated by Django 5.1.2 on 2024-11-19 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myloans', '0002_customer_firstname_customer_income_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('guarantor_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('relationship', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='loan',
            name='purpose',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='guarantor',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='myloans.guarantor'),
        ),
    ]
